# Example of a config file for connecting via a jump machine

host = "my_remote_host"
ssh_opts = ["-J", "jump_machine"]
mount_root = "/home/me/mounts/my_remote_host"

[dirs.home]
remote_expand = true  # Use bash expansion on remote host to obtain the path
remote_path = "$HOME"

[dirs.data]
remote_path = "/data/me"